[build] F: Feature switch for PIC support
nanvix/kernel pull request #433
Opened 2024-09-03 01:24 UTC by lemosep

Regarding issue #432
   * Added feature to Cargo.TOML
   * Used conditional compilation for enabling PIC support. Executing
    `cargo build` will run without PIC support. To enable PIC support run `cargo build --features "enable_pic"`

2024-09-03 01:31 UTC, lemosep commented
Two fail to execute due to the new feature flags -> [`out: Magic String: [PANIC][kernel] file='src/kmain.rs', line=332 :: interrupts must be supported
`] 
A simple approach is to reverse the flags, making the default execution contain PIC support.

2024-09-03 10:02 UTC, lemosep commented
https://github.com/nanvix/kernel/pull/433/commits/470156c795c6b6cb09fffb45100b0325e5bb6b1f -> Swaps the feature flag to `disable-pic`. Now running `cargo build` will default to enabling PIC support. To disable it, run `cargo build --features "disable-pic"`.

2024-09-03 16:00 UTC, ppenna requested changes
Hello,

As it is, this fix does not address the issue listed in the PR. You can check it from the `MicroVM` run logs (https://github.com/nanvix/kernel/actions/runs/10680687221/job/29602816566):

```
out: [WARN][kernel::hal::arch::x86::cpu::interrupt] failed to initialize 8259 pic (error=Error { code: NoSuchEntry, reason: "io port is not registered" })
out: [WARN][kernel::hal::arch::x86::cpu::interrupt::controller] new(): no interrupt controller found
out: [WARN][kernel::hal::arch::x86::cpu] failed to initialize interrupt controller (error=Error { code: NoSuchDevice, reason: "no interrupt controller found" })
out: [WARN][kernel::hal] no interrupt controller found
```

The `disable-pic` feature should be turned on for the `MicroVm` platform, as it does not have an interrupt controller.

Also, please squash commits in your PR as they are not atomically buildable and testable.

2024-09-08 19:17 UTC, ppenna commented
Closing this PR, as the branch is not following the repository conventions and pushing to branches that do not follow these rules is no longer possible.

@lemosep please, submit another PR for this once you have fixed the issue.

2024-09-08 19:17 UTC, closed without merging